apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
        type: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        
        
