apiVersion: v1
kind: Pod
metadata:
  name: red
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: redis
    image: redis
  initContainers:
  - name: busybox
    image: busybox
    command: [ "/bin/sh", "-ec", "sleep 20" ]