apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    app: multicontainer
spec:
  containers:
  - name: lemon
    image: busybox
    command: [ "/bin/sh", "-ec", "sleep 1000" ]
  - name: gold
    image: redis