apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - name: nginx-cont
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: myvol
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: claim-log-1
        