apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
data:
  MYSQL_DATABASE: c3FsMDE=
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
  MYSQL_USER: dXNlcjE=

